stages:
  - build

cmssw_compile:
  stage: build
  only:
    - gitlab-ci-build
  tags:
    - cvmfs
  variables:
    CMS_PATH: /cvmfs/cms.cern.ch
    CMSSW_RELEASE: CMSSW_10_2_15
  script:
    - /bin/bash ./.gitlab/build.sh